### ISSUE TITLE
First screen tab gets hidden when more than 12 screens are open in full-screen mode

### ISSUE THREAD

**Issue by RazSoft123** [responsively-org/responsively-app#1403]
# 🐞 bug report

When we go into full screen mode of any type of display screen in the app and when we have more than 12 screens open in the app first screen goes inside the left window in tab pane. So, it make very dificult to switch to it.

### ✍️ Description

When entering full-screen mode in Responsively, and having more than 12 device screens open simultaneously, the first screen tab gets pushed into the hidden (left) side of the tab pane, making it very difficult to access or switch back to that screen. This affects usability when testing across multiple viewports, as users often rely on the first screen for baseline comparisons or interactions.

### 🕵🏼‍♂️ Is this a regression?
I’m not sure. I haven’t tested older versions.

### 🔬 Minimal Reproduction

1. Open the Responsively App.
2. Add at least 13 device screens.
3. Enter full-screen mode.
4. Observe the tab pane the first screen tab becomes hidden inside the left side of the screen list.

### 🌍 Your Environment

**OS**: Windows 11
**App version**: v1.16.0
**App downloaded from official site**. 
**Display resolution**: 1920 X 1080

<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot

<img width="1897" height="327" alt="Image" src="https://github.com/user-attachments/assets/222df655-03f3-4726-9652-f43355bb759f" />

<pre><code>

</code></pre>

**Comment by AleksandrRise** [comment]
I will try to resolve it

**Comment by AleksandrRise** [comment]
Apparently, such an issue has been fixed in the new version. Try to update

**Comment by razsoft123** [comment]
Hello @AleksandrRise ,

I updated my app to the lateset version but the issue still persist in the app.

**Comment by rutul24591** [comment]
I'll take a look at this issue.
