### ISSUE TITLE
Table row height

### ISSUE THREAD

**Issue by BlazerYoo** [responsively-org/responsively-app#658]
# 🐞 bug report

### ✍️ Description

The last couple rows in the table here https://responsively.byoo.repl.co/ are thinner in Responsively than on actual display even though the custom device on Responsively has the same specifications as the actual display. See **🔥 Exception or Error or Screenshot** for screenshots.

### 🕵🏼‍♂️ Is this a regression?

I am not sure if this worked in the previous version.

### 🔬 Minimal Reproduction

Link to website source: https://github.com/BlazerYoo/responsively

### 🌍 Your Environment

PC

### 🔥 Exception or Error or Screenshot

Link: https://responsively.byoo.repl.co/

#### Last seven table rows in reponsively
![image](https://user-images.githubusercontent.com/69565038/149440661-0b3d7d40-70f6-4d3e-9f7f-03cb10fb71ea.png)

#### Last seven table rows on actual display
![image](https://user-images.githubusercontent.com/69565038/149440796-d402858a-d0fd-467c-80f3-84b3b6e45ca7.png)

**Comment by jjavierdguezas** [comment]
Hi @BlazerYoo, thanks for report this
I can confirm that this is happening

**Comment by GoonerBrian** [comment]
I was going to look into this but I can't run the app locally using the `yarn dev` command that is giving in `README.md` -> `Contribute`. I see in Slack that I'm not the only one to have this issue but the question wasn't addressed in Slack. This would be my first contribution and any help would be appreciated.

**Comment by danielm2402** [comment]
Hello, I was checking and found that if you are in mode: "Enable Design Mode" this is solved. I do not understand very well what this option does, could you tell me what its functionality is? If they tell me this they can assign me the ticket. Thanks!

**Comment by jjavierdguezas** [comment]
@danielm2402 I can confirm that something changes when Design Mode is activated, but it is not solved for all devices (See the laptop devices on the screenshots below)

before Design Mode is activated:
![image](https://user-images.githubusercontent.com/13673443/155102858-4d3c91f3-949e-44b5-8063-45dc3881cac2.png)

after Design Mode is activated:
![image](https://user-images.githubusercontent.com/13673443/155102948-4a360e78-04df-4d90-8d7f-b364765ada31.png)

The design mode allows you to make temporary edits to the page. (see https://developer.mozilla.org/en-US/docs/Web/API/Document/designMode)

**Comment by smsmya** [comment]
[زبراوي](https://zobrawy.com/)
[افلام سكس اغتصاب](https://zobrawy.com/category/%d8%a7%d9%81%d9%84%d8%a7%d9%85-%d8%b3%d9%83%d8%b3-%d8%a7%d8%ba%d8%aa%d8%b5%d8%a7%d8%a8/)
[افلام سكس بزاز](https://zobrawy.com/category/%d8%a7%d9%81%d9%84%d8%a7%d9%85-%d8%b3%d9%83%d8%b3-%d8%a8%d8%b2%d8%a7%d8%b2/)
[افلام سكس شواذ](https://zobrawy.com/category/%d8%a7%d9%81%d9%84%d8%a7%d9%85-%d8%b3%d9%83%d8%b3-%d8%b4%d9%88%d8%a7%d8%b0/)
[افلام سكس محارم](https://zobrawy.com/category/%d8%a7%d9%81%d9%84%d8%a7%d9%85-%d8%b3%d9%83%d8%b3-%d9%85%d8%ad%d8%a7%d8%b1%d9%85/)
[افلام سكس عربي](https://zobrawy.com/category/%d8%a7%d9%81%d9%84%d8%a7%d9%85-%d8%b3%d9%83%d8%b3-%d8%b9%d8%b1%d8%a8%d9%8a/)
[افلام سكس نار](https://zobrawy.com/category/%d8%a7%d9%81%d9%84%d8%a7%d9%85-%d8%b3%d9%83%d8%b3-%d9%86%d8%a7%d8%b1/)

**Comment by crocarneiro** [comment]
It's definitely weird and I can't seem to figure the reason out.

I was digging into this issue and found some things interesting though.

_The comments below are about the page used to test ([https://responsively.byoo.repl.co/](https://responsively.byoo.repl.co/))_

First, it only looks weird because the height of the `td` component is relative.
![image](https://user-images.githubusercontent.com/10589421/176580917-c5107ce8-263d-420b-9be2-bd84d13c280a.png)

The computed value in the first rows is (kinda) correct:
![image](https://user-images.githubusercontent.com/10589421/176581000-fd6aca06-add4-4682-aebb-80493a50d172.png)

In my case, the table’s height is `950px`, so `950x0.0476=45.22 + 4=49.22`. Rounding it up it should be `50px`, so it does not make sense. However, in the last looking okay cell the computed height is indeed `50px`.
![image](https://user-images.githubusercontent.com/10589421/176581092-6de8d99e-d2e5-4a42-9d7c-246b29537aa1.png)

As for the squished cells, their computed height is 2px.
![image](https://user-images.githubusercontent.com/10589421/176581176-46b55e75-1f5a-4e8d-8dae-bce093ce3d23.png)

But okay, let’s say we use 50px for the height instead of 4.76%. Like the image below:
![image](https://user-images.githubusercontent.com/10589421/176581740-0572af43-43a1-456d-b626-80eda33b9be2.png)

Doing this, the table is correctly rendered:
![image](https://user-images.githubusercontent.com/10589421/176581270-d630d04d-d837-4734-8322-2b3cec6f452c.png)

Actually, even if we remove the height property altogether, it renders correctly.

So, with all of this said, it would be okay to think that the problem is the percentage unit right? Actually, no. “What if I use 4% instead of 4.76%”, I thought. Result? Renders correctly. Doing more changes **I figured that it renders correctly with percentage as long as it does not have any decimals**.

But why good Lord? Is it something wrong with the chrome version we are using maybe?

I tried to update the electron version to the latest but I could not get the application running. I guess it is not that simple.

I’ll try to look a little bit more into it, but if someone has any leads I would appreciate it.

**Comment by jjavierdguezas** [comment]
https://stackoverflow.com/q/4308989

**Comment by crocarneiro** [comment]
Thanks!

Actually, I had seen this one. Not sure if I missed something on it, but It seems like they are talking about a 1 pixel difference (up or down because of the rounding). So I could not reach any conclusion about:

* Why 4.76% of 950 turns into 2px
* Why only the last rows
* Why only on Responsively
* How to fix

Seems like I'll need to give it a little more thought.

**Comment by SaunakNandi** [comment]
@crocarneiro this link is not working now [https://replit.com/replid/fdcf5459-7381-49c7-9ad4-020b61414296](url) why?

**Comment by BlazerYoo** [comment]
It should be accessible here now: https://blazeryoo.github.io/responsively/

Checking on Responsively version 1.15.0, I don't see the same issue anymore...
